### ISSUE TITLE
Settings error in matrix

### ISSUE THREAD

**Issue by Echo-Storm** [xbmc/visualization.milkdrop#24]
it seems that the settings for milkdrop are not applying, and even when setting them manually from the xml they are throwing errors. opening the settings shows this:
![Untitled](https://user-images.githubusercontent.com/67808989/115755991-f3150000-a36b-11eb-8927-e725a2413f92.png)

**Comment by AlwinEsch** [comment]
With https://github.com/xbmc/visualization.milkdrop/pull/34 becomes a fix about and shown as:
![Bildschirmfoto vom 2021-09-07 19-57-03](https://user-images.githubusercontent.com/6879739/132390447-ef053b54-56b7-4d0f-99f7-b78006454530.png)

You can take with a ZIP from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvisualization.milkdrop/detail/PR-34/2/artifacts until update is released.

**Comment by Echo-Storm** [comment]
Omg thank you so much! Amazing and so appreciated

**Comment by AlwinEsch** [comment]
The addon is now released with fix about, New addon version 19.0.0 for Kodi Matrix and the addon version 20.0.0 to Kodi Nexus. 

Thanks a lot for the report about!
